package com.example.totanpay.ui.component.dialog

object TimeContainer {
    fun getHours():List<String>{
        val h:MutableList<String> = mutableListOf()
        h.add("00")
        h.add("01")
        h.add("02")
        h.add("03")
        h.add("04")
        h.add("05")
        h.add("06")
        h.add("07")
        h.add("08")
        h.add("09")
        h.add("10")
        h.add("11")
        h.add("12")
        h.add("13")
        h.add("14")
        h.add("15")
        h.add("16")
        h.add("17")
        h.add("18")
        h.add("19")
        h.add("20")
        h.add("21")
        h.add("22")
        h.add("23")
    //    h.add("24")
        return h
    }
    fun getMinutes():List<String>{
        val h:MutableList<String> = mutableListOf()
        h.add("00")
        h.add("01")
        h.add("02")
        h.add("03")
        h.add("04")
        h.add("05")
        h.add("06")
        h.add("07")
        h.add("08")
        h.add("09")
        h.add("10")
        h.add("11")
        h.add("12")
        h.add("13")
        h.add("14")
        h.add("15")
        h.add("16")
        h.add("17")
        h.add("18")
        h.add("19")
        h.add("20")
        h.add("21")
        h.add("22")
        h.add("23")
        h.add("24")

        h.add("25")
        h.add("26")
        h.add("27")
        h.add("28")
        h.add("29")
        h.add("30")
        h.add("31")
        h.add("32")
        h.add("33")
        h.add("34")
        h.add("35")
        h.add("36")
        h.add("37")
        h.add("38")
        h.add("39")
        h.add("40")
        h.add("41")
        h.add("42")
        h.add("43")
        h.add("44")
        h.add("45")
        h.add("46")
        h.add("47")
        h.add("48")
        h.add("49")


        h.add("50")
        h.add("51")
        h.add("52")
        h.add("53")
        h.add("54")
        h.add("55")
        h.add("56")
        h.add("57")
        h.add("58")
        h.add("59")

        return h
    }

}